"""
Django settings for WebApp project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

from pathlib import Path
import os


# Initialise my env variables. 
# Because I don't want to expose e-mail and password in a public repository duh
# You'll have to use your own,
kazuland_email = os.environ.get('EMAIL_USER')
kazuland_pass = os.environ.get('EMAIL_PASS')


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# I didn't have to to this but.... use your own secret key too. xD. 
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'WebApp.apps.WebAppConfig',
    'blog.apps.BlogConfig',
    'users.apps.UsersConfig',
    'tracker.apps.TrackerConfig',
    'crispy_forms',
    'crispy_bootstrap4',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

"""
Bellow, this means that the WebApp/urls.py is the location to look for paths of the aplication.
 Other Apps have their own urls.py, but they are located only after (and if) the WebApp/urls.py 
 pointed to their respective urls.py file.
"""
ROOT_URLCONF = 'WebApp.urls'


"""
Bellow, this will implement the Django convention to look for templates inside each App's respective 
"templates" folder.
The convention is: "the ExempleApp's templates will be in "ExempleApp/templates/ExempleApp/"
"""
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# See the wsgi.py notes
WSGI_APPLICATION = 'WebApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
# I'm telling django that the database is the sqlite3, and we'll call it "db.sqlite3"
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
# Just telling django where to find the static files, like js scripts, css files and some images 
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# The crispy template pack is referenced in some points of the application and it
#  will load bootstrap4 for my project
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# this will be referenced in the Users view. It's the page that django will
# redirect to after a sucessful login.
LOGIN_REDIRECT_URL = 'realHome'
LOGIN_URL = 'login'

# These are the configurations for email server.
# You have to use your own email host and email password.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = kazuland_email #see line 22
EMAIL_HOST_PASSWORD = kazuland_pass #see line 23
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

